#:schema node_modules/wrangler/config-schema.json
name = "kdafov-services-worker"
main = "src/index.ts"
compatibility_date = "2024-12-24"

# Workers Logs
[observability.logs]
enabled = true

# Database
[[d1_databases]]
binding = "DB"
database_name = "${db_name}"
database_id = "${id}"