#:schema node_modules/wrangler/config-schema.json
name = "word-service"
main = "src/index.ts"
compatibility_date = "2024-12-18"

# Workers Logs
[observability.logs]
enabled = true

# Development Environment
[[env.dev.d1_databases]]
binding = "DB_DEV"
database_name = "minigame-db-local"
database_id = "${local_db_id}"

# Production Environment
[[env.production.d1_databases]]
binding = "DB_PROD"
database_name = "minigame-db"
database_id = "${prod_db_id}"